### ISSUE TITLE
Patch 68

### ISSUE THREAD

**Issue by pankixoi2113** [pouyadarabi/Instagram_SSL_Pinning#21] opened 2018-10-18 13:46 UTC
Does anyone have patched apk with this version?

**Comment by dakiesse** [comment] 2018-10-23 21:31
up

**Comment by dakiesse** [comment] 2018-10-23 21:31
@pankixoi2113 did you find something?

**Comment by bravepuzzle** [comment] 2018-10-31 17:11
@pouyadarabi any chance you could update the latest version? thanks.

**Comment by pouyadarabi** [comment] 2019-01-10 07:27
Duplicate of #23

**Closed as completed by pouyadarabi** 2019-01-10 07:27 UTC
