### ISSUE TITLE
Please update the modified APKs to the latest IG version for IGTV

### ISSUE THREAD

**Issue by cloudzero-zz** [pouyadarabi/Instagram_SSL_Pinning#22] opened 2018-11-06 19:42 UTC
Looking desperately for IGTV api's, please update the modded APKs to the latest IG app

**Comment by AmaHacka** [comment] 2018-11-08 11:35
up

**Comment by oliverbytes** [comment] 2019-01-04 08:26
Can anyone tell me where is the instruction link?

**Comment by pouyadarabi** [comment] 2019-01-10 07:26
Duplicate of #23

**Closed as completed by pouyadarabi** 2019-01-10 07:26 UTC
